name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: pip install molecule docker molecule-docker ansible flake8 ansible-lint
      name: Install molecule

    - run: molecule test
      name: Test
